[package]
name = "vimail"
version = "0.1.0"
edition = "2021"

[dependencies]
once_cell = "1.19.0"
reqwest = "0.11.26"
rss = "2.0.7"
serde = { version="1.0.197", features=["derive"] }
serde_json = "1.0.115"
signal-hook = "0.3.17"
termion = "3.0.0"
tokio = "1.36.0"
